server:
  port: 4396
spring:
  http:
    multipart:
  application:
    name: hsport
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hsport?characterEncoding=utf8
      username: root
      password: 123456
mybatis-plus:
  mapper-locations: classpath:com/hsport/wxprogram/mapper/*Mapper.xml
  type-aliases-package: com.hsport.wxprogram.domain,com.hsport.wxprogram.query
logging:
  level:
    com.hsport.*: debug
  file:
    name: wxprogram.log
jedis:
  host: 127.0.0.1
  port: 6379
  pool:
    max-idle: 300
    min-idle: 10
    max-total: 600
    max-wait: 1000
    block-when-exhausted: true
    
